package GUI;

import Logic.*;
import Util.Direction;
import Util.Movement;
import Util.Point;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JFrame;

/**
 *
 * @author Hume
 */
public class GUI extends JFrame{

    /**
     * Creates new form NewJFrame
     * @param t
     * @param b
     */
    public GUI(Thread t) throws IOException {
        initComponents();        
        /* SET TAGS PROPERTIES*/        
        Jugador1.setEditable(false);
        Jugador2.setEditable(false);
        
        BufferedImage image = ImageIO.read(getClass().getResource("/resources/Othello.jpg"));
        
        ImageIcon n = new ImageIcon(resize(image,jLabel19.getWidth(),jLabel19.getHeight()));
        
        jLabel19.setIcon(n);
        
        
        
        /* SET VARIABLES */        
        s=null;
        pare = t;
        
        /* INTERRUPT FATHER*/
        pare.interrupt();        
    }
    
    public static BufferedImage resize(BufferedImage img, int newW, int newH) { 
    Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
    BufferedImage dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

    Graphics2D g2d = dimg.createGraphics();
    g2d.drawImage(tmp, 0, 0, null);
    g2d.dispose();

    return dimg;
}  
    
    
    // Private
    boolean acabat = false;
    Thread pare = null;
    Board b = null;
    Vector<Movement> mov = null; 
    private Point s;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        fill_73 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_03 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_33 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_43 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_53 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_63 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_74 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_64 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_54 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_34 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_04 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_72 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_62 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_52 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_42 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_22 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_02 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_75 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_65 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_55 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_45 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_35 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_05 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_76 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_66 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_56 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_46 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_06 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_71 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_61 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_51 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_41 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_31 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_01 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_57 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_47 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_37 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_07 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_67 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_77 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_70 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_60 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_50 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_40 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_00 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Jugador1 = new javax.swing.JTextField();
        Jugador2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TurnLabel = new javax.swing.JLabel();
        LabelColor = new javax.swing.JLabel();
        pj1 = new javax.swing.JLabel();
        pecesj1 = new javax.swing.JLabel();
        pj2 = new javax.swing.JLabel();
        pecesj2 = new javax.swing.JLabel();
        WLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratoliPres(evt);
            }
        });

        fill_73.setBackground(new java.awt.Color(0, 153, 51));
        fill_73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_73.setOpaque(true);
        jLayeredPane1.add(fill_73);
        fill_73.setBounds(150, 0, 50, 50);

        fill_03.setBackground(new java.awt.Color(0, 153, 51));
        fill_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_03.setOpaque(true);
        jLayeredPane1.add(fill_03);
        fill_03.setBounds(150, 350, 50, 50);

        fill_13.setBackground(new java.awt.Color(0, 153, 51));
        fill_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_13.setOpaque(true);
        jLayeredPane1.add(fill_13);
        fill_13.setBounds(150, 300, 50, 50);

        fill_23.setBackground(new java.awt.Color(0, 153, 51));
        fill_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_23.setOpaque(true);
        jLayeredPane1.add(fill_23);
        fill_23.setBounds(150, 250, 50, 50);

        fill_33.setBackground(new java.awt.Color(0, 153, 51));
        fill_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_33.setOpaque(true);
        jLayeredPane1.add(fill_33);
        fill_33.setBounds(150, 200, 50, 50);

        fill_43.setBackground(new java.awt.Color(0, 153, 51));
        fill_43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_43.setOpaque(true);
        jLayeredPane1.add(fill_43);
        fill_43.setBounds(150, 150, 50, 50);

        fill_53.setBackground(new java.awt.Color(0, 153, 51));
        fill_53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_53.setOpaque(true);
        jLayeredPane1.add(fill_53);
        fill_53.setBounds(150, 100, 50, 50);

        fill_63.setBackground(new java.awt.Color(0, 153, 51));
        fill_63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_63.setOpaque(true);
        jLayeredPane1.add(fill_63);
        fill_63.setBounds(150, 50, 50, 50);

        fill_74.setBackground(new java.awt.Color(0, 153, 51));
        fill_74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_74.setOpaque(true);
        jLayeredPane1.add(fill_74);
        fill_74.setBounds(200, 0, 50, 50);

        fill_64.setBackground(new java.awt.Color(0, 153, 51));
        fill_64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_64.setOpaque(true);
        jLayeredPane1.add(fill_64);
        fill_64.setBounds(200, 50, 50, 50);

        fill_54.setBackground(new java.awt.Color(0, 153, 51));
        fill_54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_54.setOpaque(true);
        jLayeredPane1.add(fill_54);
        fill_54.setBounds(200, 100, 50, 50);

        fill_44.setBackground(new java.awt.Color(0, 153, 51));
        fill_44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_44.setOpaque(true);
        jLayeredPane1.add(fill_44);
        fill_44.setBounds(200, 150, 50, 50);

        fill_34.setBackground(new java.awt.Color(0, 153, 51));
        fill_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_34.setOpaque(true);
        jLayeredPane1.add(fill_34);
        fill_34.setBounds(200, 200, 50, 50);

        fill_24.setBackground(new java.awt.Color(0, 153, 51));
        fill_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_24.setOpaque(true);
        jLayeredPane1.add(fill_24);
        fill_24.setBounds(200, 250, 50, 50);

        fill_14.setBackground(new java.awt.Color(0, 153, 51));
        fill_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_14.setOpaque(true);
        jLayeredPane1.add(fill_14);
        fill_14.setBounds(200, 300, 50, 50);

        fill_04.setBackground(new java.awt.Color(0, 153, 51));
        fill_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_04.setOpaque(true);
        jLayeredPane1.add(fill_04);
        fill_04.setBounds(200, 350, 50, 50);

        fill_72.setBackground(new java.awt.Color(0, 153, 51));
        fill_72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_72.setOpaque(true);
        jLayeredPane1.add(fill_72);
        fill_72.setBounds(100, 0, 50, 50);

        fill_62.setBackground(new java.awt.Color(0, 153, 51));
        fill_62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_62.setOpaque(true);
        jLayeredPane1.add(fill_62);
        fill_62.setBounds(100, 50, 50, 50);

        fill_52.setBackground(new java.awt.Color(0, 153, 51));
        fill_52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_52.setOpaque(true);
        jLayeredPane1.add(fill_52);
        fill_52.setBounds(100, 100, 50, 50);

        fill_42.setBackground(new java.awt.Color(0, 153, 51));
        fill_42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_42.setOpaque(true);
        jLayeredPane1.add(fill_42);
        fill_42.setBounds(100, 150, 50, 50);

        fill_32.setBackground(new java.awt.Color(0, 153, 51));
        fill_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_32.setOpaque(true);
        jLayeredPane1.add(fill_32);
        fill_32.setBounds(100, 200, 50, 50);

        fill_22.setBackground(new java.awt.Color(0, 153, 51));
        fill_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_22.setOpaque(true);
        jLayeredPane1.add(fill_22);
        fill_22.setBounds(100, 250, 50, 50);

        fill_12.setBackground(new java.awt.Color(0, 153, 51));
        fill_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_12.setOpaque(true);
        jLayeredPane1.add(fill_12);
        fill_12.setBounds(100, 300, 50, 50);

        fill_02.setBackground(new java.awt.Color(0, 153, 51));
        fill_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_02.setOpaque(true);
        jLayeredPane1.add(fill_02);
        fill_02.setBounds(100, 350, 50, 50);

        fill_75.setBackground(new java.awt.Color(0, 153, 51));
        fill_75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_75.setOpaque(true);
        jLayeredPane1.add(fill_75);
        fill_75.setBounds(250, 0, 50, 50);

        fill_65.setBackground(new java.awt.Color(0, 153, 51));
        fill_65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_65.setOpaque(true);
        jLayeredPane1.add(fill_65);
        fill_65.setBounds(250, 50, 50, 50);

        fill_55.setBackground(new java.awt.Color(0, 153, 51));
        fill_55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_55.setOpaque(true);
        jLayeredPane1.add(fill_55);
        fill_55.setBounds(250, 100, 50, 50);

        fill_45.setBackground(new java.awt.Color(0, 153, 51));
        fill_45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_45.setOpaque(true);
        jLayeredPane1.add(fill_45);
        fill_45.setBounds(250, 150, 50, 50);

        fill_35.setBackground(new java.awt.Color(0, 153, 51));
        fill_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_35.setOpaque(true);
        jLayeredPane1.add(fill_35);
        fill_35.setBounds(250, 200, 50, 50);

        fill_25.setBackground(new java.awt.Color(0, 153, 51));
        fill_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_25.setOpaque(true);
        jLayeredPane1.add(fill_25);
        fill_25.setBounds(250, 250, 50, 50);

        fill_15.setBackground(new java.awt.Color(0, 153, 51));
        fill_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_15.setOpaque(true);
        jLayeredPane1.add(fill_15);
        fill_15.setBounds(250, 300, 50, 50);

        fill_05.setBackground(new java.awt.Color(0, 153, 51));
        fill_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_05.setOpaque(true);
        jLayeredPane1.add(fill_05);
        fill_05.setBounds(250, 350, 50, 50);

        fill_76.setBackground(new java.awt.Color(0, 153, 51));
        fill_76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_76.setOpaque(true);
        jLayeredPane1.add(fill_76);
        fill_76.setBounds(300, 0, 50, 50);

        fill_66.setBackground(new java.awt.Color(0, 153, 51));
        fill_66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_66.setOpaque(true);
        jLayeredPane1.add(fill_66);
        fill_66.setBounds(300, 50, 50, 50);

        fill_56.setBackground(new java.awt.Color(0, 153, 51));
        fill_56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_56.setOpaque(true);
        jLayeredPane1.add(fill_56);
        fill_56.setBounds(300, 100, 50, 50);

        fill_46.setBackground(new java.awt.Color(0, 153, 51));
        fill_46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_46.setOpaque(true);
        jLayeredPane1.add(fill_46);
        fill_46.setBounds(300, 150, 50, 50);

        fill_36.setBackground(new java.awt.Color(0, 153, 51));
        fill_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_36.setOpaque(true);
        jLayeredPane1.add(fill_36);
        fill_36.setBounds(300, 200, 50, 50);

        fill_26.setBackground(new java.awt.Color(0, 153, 51));
        fill_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_26.setOpaque(true);
        jLayeredPane1.add(fill_26);
        fill_26.setBounds(300, 250, 50, 50);

        fill_16.setBackground(new java.awt.Color(0, 153, 51));
        fill_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_16.setOpaque(true);
        jLayeredPane1.add(fill_16);
        fill_16.setBounds(300, 300, 50, 50);

        fill_06.setBackground(new java.awt.Color(0, 153, 51));
        fill_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_06.setOpaque(true);
        jLayeredPane1.add(fill_06);
        fill_06.setBounds(300, 350, 50, 50);

        fill_71.setBackground(new java.awt.Color(0, 153, 51));
        fill_71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_71.setOpaque(true);
        jLayeredPane1.add(fill_71);
        fill_71.setBounds(50, 0, 50, 50);

        fill_61.setBackground(new java.awt.Color(0, 153, 51));
        fill_61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_61.setOpaque(true);
        jLayeredPane1.add(fill_61);
        fill_61.setBounds(50, 50, 50, 50);

        fill_51.setBackground(new java.awt.Color(0, 153, 51));
        fill_51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_51.setOpaque(true);
        jLayeredPane1.add(fill_51);
        fill_51.setBounds(50, 100, 50, 50);

        fill_41.setBackground(new java.awt.Color(0, 153, 51));
        fill_41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_41.setOpaque(true);
        jLayeredPane1.add(fill_41);
        fill_41.setBounds(50, 150, 50, 50);

        fill_31.setBackground(new java.awt.Color(0, 153, 51));
        fill_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_31.setOpaque(true);
        jLayeredPane1.add(fill_31);
        fill_31.setBounds(50, 200, 50, 50);

        fill_21.setBackground(new java.awt.Color(0, 153, 51));
        fill_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_21.setOpaque(true);
        jLayeredPane1.add(fill_21);
        fill_21.setBounds(50, 250, 50, 50);

        fill_11.setBackground(new java.awt.Color(0, 153, 51));
        fill_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_11.setOpaque(true);
        jLayeredPane1.add(fill_11);
        fill_11.setBounds(50, 300, 50, 50);

        fill_01.setBackground(new java.awt.Color(0, 153, 51));
        fill_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_01.setOpaque(true);
        jLayeredPane1.add(fill_01);
        fill_01.setBounds(50, 350, 50, 50);

        fill_57.setBackground(new java.awt.Color(0, 153, 51));
        fill_57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_57.setOpaque(true);
        jLayeredPane1.add(fill_57);
        fill_57.setBounds(350, 100, 50, 50);

        fill_47.setBackground(new java.awt.Color(0, 153, 51));
        fill_47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_47.setOpaque(true);
        jLayeredPane1.add(fill_47);
        fill_47.setBounds(350, 150, 50, 50);

        fill_37.setBackground(new java.awt.Color(0, 153, 51));
        fill_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_37.setOpaque(true);
        jLayeredPane1.add(fill_37);
        fill_37.setBounds(350, 200, 50, 50);

        fill_27.setBackground(new java.awt.Color(0, 153, 51));
        fill_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_27.setOpaque(true);
        jLayeredPane1.add(fill_27);
        fill_27.setBounds(350, 250, 50, 50);

        fill_07.setBackground(new java.awt.Color(0, 153, 51));
        fill_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_07.setOpaque(true);
        jLayeredPane1.add(fill_07);
        fill_07.setBounds(350, 350, 50, 50);

        fill_17.setBackground(new java.awt.Color(0, 153, 51));
        fill_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_17.setOpaque(true);
        jLayeredPane1.add(fill_17);
        fill_17.setBounds(350, 300, 50, 50);

        fill_67.setBackground(new java.awt.Color(0, 153, 51));
        fill_67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_67.setOpaque(true);
        jLayeredPane1.add(fill_67);
        fill_67.setBounds(350, 50, 50, 50);

        fill_77.setBackground(new java.awt.Color(0, 153, 51));
        fill_77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_77.setOpaque(true);
        jLayeredPane1.add(fill_77);
        fill_77.setBounds(350, 0, 50, 50);

        fill_70.setBackground(new java.awt.Color(0, 153, 51));
        fill_70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_70.setOpaque(true);
        jLayeredPane1.add(fill_70);
        fill_70.setBounds(0, 0, 50, 50);

        fill_60.setBackground(new java.awt.Color(0, 153, 51));
        fill_60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_60.setOpaque(true);
        jLayeredPane1.add(fill_60);
        fill_60.setBounds(0, 50, 50, 50);

        fill_50.setBackground(new java.awt.Color(0, 153, 51));
        fill_50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_50.setOpaque(true);
        jLayeredPane1.add(fill_50);
        fill_50.setBounds(0, 100, 50, 50);

        fill_40.setBackground(new java.awt.Color(0, 153, 51));
        fill_40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_40.setOpaque(true);
        jLayeredPane1.add(fill_40);
        fill_40.setBounds(0, 150, 50, 50);

        fill_30.setBackground(new java.awt.Color(0, 153, 51));
        fill_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_30.setOpaque(true);
        jLayeredPane1.add(fill_30);
        fill_30.setBounds(0, 200, 50, 50);

        fill_20.setBackground(new java.awt.Color(0, 153, 51));
        fill_20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_20.setOpaque(true);
        jLayeredPane1.add(fill_20);
        fill_20.setBounds(0, 250, 50, 50);

        fill_10.setBackground(new java.awt.Color(0, 153, 51));
        fill_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_10.setOpaque(true);
        jLayeredPane1.add(fill_10);
        fill_10.setBounds(0, 300, 50, 50);

        fill_00.setBackground(new java.awt.Color(0, 153, 51));
        fill_00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_00.setOpaque(true);
        jLayeredPane1.add(fill_00);
        fill_00.setBounds(0, 350, 50, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("7");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("6");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("5");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("4");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("2");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("1");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("0");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("A");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("B");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("C");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("D");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("E");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("F");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("G");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("H");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VS");

        jLabel18.setText("Turn :");

        TurnLabel.setText("UNDEFINED");

        LabelColor.setText("UNDEFINED");

        pj1.setText("Peces J1:");

        pecesj1.setText("UF");

        pj2.setText("Peces J2:");

        pecesj2.setText("UF");

        WLabel.setText("OTHELLO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TurnLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jugador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Jugador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pj1)
                                .addComponent(LabelColor)
                                .addComponent(pj2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pecesj1)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pecesj2)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(WLabel)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WLabel)
                .addGap(33, 33, 33)
                .addComponent(Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TurnLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelColor)
                .addGap(18, 18, 18)
                .addComponent(pj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pecesj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pj2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pecesj2)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>                        

    private void ratoliPres(java.awt.event.MouseEvent evt) {                            
        /* OBTAIN MOUSE POSITION */
        int rata_x = evt.getX();
        int rata_y = evt.getY();
        double pan_x = jLayeredPane1.getSize().getWidth();
        double pan_y = jLayeredPane1.getSize().getHeight();
        
        int fila = rata_x / 8;
        int col = rata_y / 8;
                
        int aux = (int) (rata_x / (pan_x / 8 ));
        int aux2 = (int) (rata_y / (pan_y / 8));
        s = new Point (aux2,aux);
        
        /* INTERRUPT Othello*/
        pare.interrupt();
    }                           
   
    public Point getPoint(){return s;}
  
    /* SETTERS */
    public void updateBoard(Board b){this.b=b;}
    public void updateMov (Vector<Movement> mov){this.mov = mov;}
    public void setTurn (String s, int t){TurnLabel.setText(s);    
        if (t == 1) LabelColor.setText("Negres");
        else if (t == -1) LabelColor.setText("Blanques");        
    }   
    public void setWinner(String s){
        jLabel18.setVisible(false);
        TurnLabel.setVisible(false);
        pj1.setVisible(false);
        pecesj1.setVisible(false);
        pj2.setVisible(false);
        pecesj2.setVisible(false);
        
       // WLabel.setText("Winner: " + s);
       WLabel.setText("<html>Winner :<br/>"+s+"</html>");
        
    }
    public void setNumPieces(int j1, int j2){
        pecesj1.setText(Integer.toString(j1));
        pecesj2.setText(Integer.toString(j2));
    }
    
    
    
    
    public void pinta_tauler(Board b, Vector<Movement> mov)
    {
        updateBoard(b);
        updateMov(mov);
        repaint();
        
    }
    
    
    
    
     @Override
    public void paint(Graphics g)
    {
        int [][] tauler = b.getBoard();
        
        System.out.println("TENDRIA Q PINTAR ESTO");
        for (int i=0;i<8;++i){
                for (int j=0;j<8;++j){
                    System.out.print(tauler[i][j]+" ");
                }
                System.out.println("");
        }
        
        super.paint(g);
        for (int i=0; i<8; i++){
            for (int j=0; j<8; j++){
                
                if (tauler[i][j] == 1){
                    g.setColor(Color.BLACK);
                    g.drawOval(whichx(j),whichy(i),40,40);
                    g.fillOval(whichx(j),whichy(i),40,40);                
                }
                else if (tauler[i][j] == -1 ){
                    g.setColor(Color.WHITE);
                    g.drawOval(whichx(j),whichy(i),40,40);
                    g.fillOval(whichx(j),whichy(i),40,40);

                }
                
                if (i < mov.size()){
                    Point p = mov.get(i).getPosition();
                    g.setColor(Color.RED);
                    g.drawOval(whichx(p.getY()),whichy(p.getX()),40,40);
                    g.setColor(new Color (0,175,0));
                    g.fillOval(whichx(p.getY()),whichy(p.getX()),40,40);
                    
                    if (j==0) System.out.println("Point "+p.toString() + " con direcciones "+Direction.getDirs(mov.get(i).getDirections()));
                }

            }
        }
        
        
     
    }
    
        
    private static int whichx(int col){
        return ((50*col+52));
    }
    
    private static int whichy(int fil){
        return (50*fil+85+42);
    }
    
    
    public void setPlayers(String p1,String p2){Jugador1.setText(p1);
        Jugador2.setText(p2);
    }
    public void setStatus(String s){pecesj1.setText(s);}
    
    
    




    // Variables declaration - do not modify                     
    private javax.swing.JTextField Jugador1;
    private javax.swing.JTextField Jugador2;
    private javax.swing.JLabel LabelColor;
    private javax.swing.JLabel TurnLabel;
    private javax.swing.JLabel WLabel;
    private javax.swing.Box.Filler fill_00;
    private javax.swing.Box.Filler fill_01;
    private javax.swing.Box.Filler fill_02;
    private javax.swing.Box.Filler fill_03;
    private javax.swing.Box.Filler fill_04;
    private javax.swing.Box.Filler fill_05;
    private javax.swing.Box.Filler fill_06;
    private javax.swing.Box.Filler fill_07;
    private javax.swing.Box.Filler fill_10;
    private javax.swing.Box.Filler fill_11;
    private javax.swing.Box.Filler fill_12;
    private javax.swing.Box.Filler fill_13;
    private javax.swing.Box.Filler fill_14;
    private javax.swing.Box.Filler fill_15;
    private javax.swing.Box.Filler fill_16;
    private javax.swing.Box.Filler fill_17;
    private javax.swing.Box.Filler fill_20;
    private javax.swing.Box.Filler fill_21;
    private javax.swing.Box.Filler fill_22;
    private javax.swing.Box.Filler fill_23;
    private javax.swing.Box.Filler fill_24;
    private javax.swing.Box.Filler fill_25;
    private javax.swing.Box.Filler fill_26;
    private javax.swing.Box.Filler fill_27;
    private javax.swing.Box.Filler fill_30;
    private javax.swing.Box.Filler fill_31;
    private javax.swing.Box.Filler fill_32;
    private javax.swing.Box.Filler fill_33;
    private javax.swing.Box.Filler fill_34;
    private javax.swing.Box.Filler fill_35;
    private javax.swing.Box.Filler fill_36;
    private javax.swing.Box.Filler fill_37;
    private javax.swing.Box.Filler fill_40;
    private javax.swing.Box.Filler fill_41;
    private javax.swing.Box.Filler fill_42;
    private javax.swing.Box.Filler fill_43;
    private javax.swing.Box.Filler fill_44;
    private javax.swing.Box.Filler fill_45;
    private javax.swing.Box.Filler fill_46;
    private javax.swing.Box.Filler fill_47;
    private javax.swing.Box.Filler fill_50;
    private javax.swing.Box.Filler fill_51;
    private javax.swing.Box.Filler fill_52;
    private javax.swing.Box.Filler fill_53;
    private javax.swing.Box.Filler fill_54;
    private javax.swing.Box.Filler fill_55;
    private javax.swing.Box.Filler fill_56;
    private javax.swing.Box.Filler fill_57;
    private javax.swing.Box.Filler fill_60;
    private javax.swing.Box.Filler fill_61;
    private javax.swing.Box.Filler fill_62;
    private javax.swing.Box.Filler fill_63;
    private javax.swing.Box.Filler fill_64;
    private javax.swing.Box.Filler fill_65;
    private javax.swing.Box.Filler fill_66;
    private javax.swing.Box.Filler fill_67;
    private javax.swing.Box.Filler fill_70;
    private javax.swing.Box.Filler fill_71;
    private javax.swing.Box.Filler fill_72;
    private javax.swing.Box.Filler fill_73;
    private javax.swing.Box.Filler fill_74;
    private javax.swing.Box.Filler fill_75;
    private javax.swing.Box.Filler fill_76;
    private javax.swing.Box.Filler fill_77;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pecesj1;
    private javax.swing.JLabel pecesj2;
    private javax.swing.JLabel pj1;
    private javax.swing.JLabel pj2;
    // End of variables declaration                   
}
