/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.GUI.resize;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author marti
 */
public class Pick extends javax.swing.JDialog {
    private JPanel panel2;
    private JLabel lblBackgroundImage = new JLabel();
    
    private int prof1,prof2;
    private String user1="UF",user2="UF";
    
    Thread pare;
    
    
    public static BufferedImage resize(BufferedImage img, int newW, int newH) { 
        Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        BufferedImage dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g2d = dimg.createGraphics();
        g2d.drawImage(tmp, 0, 0, null);
        g2d.dispose();
        return dimg;
    }  
    
    

    /**
     * Creates new form Pick
     */
    public Pick(GUI parent, boolean modal, Thread pare) throws IOException {
        super(parent, modal);
        initComponents();
        
        panel2 = new JPanel();
        panel2.setOpaque(false);
        panel2.setLayout(new FlowLayout());
        this.pare = pare;
        
        lblBackgroundImage.setLayout(new FlowLayout());
        
        BufferedImage image = ImageIO.read(getClass().getResource  ("/resources/Background.jpg"));  
        
        lblBackgroundImage.setIcon(new ImageIcon(resize(image,100,getHeight())));
        lblBackgroundImage.setLayout(new BorderLayout());
        
        
        
      //  BufferedImage image = ImageIO.read(getClass().getResource  ("/resources/Othello.jpg"));        
      //  ImageIcon n = new ImageIcon(resize(image,jLabel19.getWidth(),jLabel19.getHeight()));        
      //  jLabel19.setIcon(n);
      
        lblBackgroundImage.add(panel2);

        add(lblBackgroundImage);
        
        System.out.println("CONSTRUIT");
        
        this.setBackground(Color.RED);

        prof1=prof2=0;
        user1=Rulet.getItemAt(Rulet.getSelectedIndex());
        user2=Rulet2.getItemAt(Rulet2.getSelectedIndex());
        
        pare.interrupt();
        
        
        
        
    }
    
    
    
    public Pair getChoice()
    {
        
        System.out.println("ENTRO");
        
        if (user1 == "LloydC" && user2 != "LloydC") return new Pair(user1+"-"+prof1,user2);
        else if (user1 == "LloydC" && user2 == "LloydC") return new Pair (user1+"-"+prof1,user2+"-"+prof2);
        else if (user1 != "LloydC" && user2 != "LloydC") return new Pair (user1,user2);
        else return new Pair (user1,user2+"-"+prof2);
        
        
        
       /* if (Rulet.getItemAt(Rulet.getSelectedIndex()) == "LloydC"){           
            
            if (Rulet2.getItemAt(Rulet2.getSelectedIndex()) == "LloydC"){
                return new Pair(Rulet.getItemAt(Rulet.getSelectedIndex())+"-"+prof1,Rulet2.getItemAt(Rulet2.getSelectedIndex())+"-"+prof2);                
            }
            else return new Pair(Rulet.getItemAt(Rulet.getSelectedIndex())+"-"+prof1,Rulet2.getItemAt(Rulet2.getSelectedIndex()));                        
        }        
        else{
            if (Rulet2.getItemAt(Rulet2.getSelectedIndex()) == "LloydC"){
                return new Pair(Rulet.getItemAt(Rulet.getSelectedIndex()),Rulet2.getItemAt(Rulet2.getSelectedIndex())+"-"+prof2);       
            }
            
            else return new Pair(Rulet.getItemAt(Rulet.getSelectedIndex()),Rulet2.getItemAt(Rulet2.getSelectedIndex()));
        }*/
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rulet2 = new javax.swing.JComboBox<>();
        Rulet = new javax.swing.JComboBox<>();
        BGo = new javax.swing.JButton();
        PCombo = new javax.swing.JComboBox<>();
        PCombo2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PICK YOUR PLAYERS");

        jLabel2.setText("P1 : ");

        jLabel3.setText("P2 : ");

        Rulet2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Random", "LloydC" }));
        Rulet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rulet2ActionPerformed(evt);
            }
        });

        Rulet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Random", "LloydC" }));
        Rulet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuletActionPerformed(evt);
            }
        });

        BGo.setText("GO");
        BGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGoActionPerformed(evt);
            }
        });

        PCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        PCombo.setEnabled(false);
        PCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PComboActionPerformed(evt);
            }
        });

        PCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        PCombo2.setEnabled(false);
        PCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCombo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rulet2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(PCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rulet, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(BGo)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Rulet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Rulet2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGo)
                    .addComponent(PCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGoActionPerformed
        // TODO add your handling code here:
        
        
        
        pare.interrupt();
        try {
            Thread.sleep(50);
        } catch (InterruptedException ex) {
            Logger.getLogger(Pick.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_BGoActionPerformed

    private void RuletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuletActionPerformed
        // TODO add your handling code here:
        if (Rulet.getItemAt(Rulet.getSelectedIndex()) == "LloydC"){
            PCombo.setEnabled(true);
            prof1 = Integer.valueOf(PCombo.getItemAt(PCombo.getSelectedIndex()));            
        }
        else PCombo.setEnabled(false);
        user1 = Rulet.getItemAt(Rulet.getSelectedIndex());
    }//GEN-LAST:event_RuletActionPerformed

    private void PCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCombo2ActionPerformed
        // TODO add your handling code here:
        prof2=Integer.parseInt(PCombo2.getItemAt(PCombo2.getSelectedIndex()));
       
    }//GEN-LAST:event_PCombo2ActionPerformed

    private void Rulet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rulet2ActionPerformed
        // TODO add your handling code here:
         if (Rulet2.getItemAt(Rulet2.getSelectedIndex()) == "LloydC"){
            PCombo2.setEnabled(true);
            prof2 = Integer.valueOf(PCombo2.getItemAt(PCombo2.getSelectedIndex()));            
        }
        else PCombo2.setEnabled(false);
        user2 = Rulet2.getItemAt(Rulet2.getSelectedIndex());
    }//GEN-LAST:event_Rulet2ActionPerformed

    private void PComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PComboActionPerformed
        // TODO add your handling code here:
        prof1= Integer.parseInt(PCombo.getItemAt(PCombo.getSelectedIndex()));
    }//GEN-LAST:event_PComboActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGo;
    private javax.swing.JComboBox<String> PCombo;
    private javax.swing.JComboBox<String> PCombo2;
    private javax.swing.JComboBox<String> Rulet;
    private javax.swing.JComboBox<String> Rulet2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
