package epsevg.eu.Othello.GUI;

import epsevg.eu.Othello.Base.Options;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.util.Pair;

public class Pick extends javax.swing.JDialog {
    
    private int prof1,prof2;
    private String user1,user2;       
    private Thread pare;
    
    public Pick(GUI parent, boolean modal, Thread pare, Options exjugadors) throws IOException {
        super(parent, modal);
        initComponents();
        
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
                
            }
        });
        
        this.pare = pare;
        
        if (exjugadors != null){
            
            user1 = exjugadors.getFirstPlayer();
            user2 = exjugadors.getSecondPlayer();
            
            prof1 = exjugadors.getP1Prof();
            prof2 = exjugadors.getP2Prof();
            
            if (!"Manual".equals(user1) && !"Random".equals(user1))
            {
                PCombo.setSelectedItem(String.valueOf(prof1));
            }
                
            if (!"Manual".equals(user2) && !"Random".equals(user2))
            {
                PCombo2.setSelectedItem(String.valueOf(prof2));                
            }
            
            
            Rulet.setSelectedItem(user1);
            Rulet2.setSelectedItem(user2);
            
        }
        
        
        else{
            System.out.println("First Game");
            prof1=prof2=0;
            user1=Rulet.getItemAt(Rulet.getSelectedIndex());
            user2=Rulet2.getItemAt(Rulet2.getSelectedIndex());
            
        }
        
        this.setTitle("Othello - Reversi");
        this.getRootPane().setDefaultButton(BGo);
        
        pare.interrupt();
        
        
    }
    
    
    
    public Pair<String[],String[]> getChoice()
    {
        String[] aux1 = new String[3];
        String[] aux2 = new String[3];
        
        aux1[0] = user1;
        aux1[1] = String.valueOf(prof1);
        
        aux2[0] = user2;
        aux2[1] = String.valueOf(prof2);
        
        return new Pair(aux1,aux2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Rulet2 = new javax.swing.JComboBox<>();
        Rulet = new javax.swing.JComboBox<>();
        BGo = new javax.swing.JButton();
        PCombo = new javax.swing.JComboBox<>();
        PCombo2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PICK YOUR PLAYERS");

        jLabel2.setText("P1 : ");

        jLabel3.setText("P2 : ");

        Rulet2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Random", "LloydC" }));
        Rulet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rulet2ActionPerformed(evt);
            }
        });

        Rulet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Random", "LloydC" }));
        Rulet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuletActionPerformed(evt);
            }
        });

        BGo.setText("GO");
        BGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGoActionPerformed(evt);
            }
        });

        PCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        PCombo.setEnabled(false);
        PCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PComboActionPerformed(evt);
            }
        });

        PCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        PCombo2.setEnabled(false);
        PCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCombo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rulet, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rulet2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PCombo, 0, 73, Short.MAX_VALUE)
                            .addComponent(PCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BGo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Rulet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Rulet2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(BGo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGoActionPerformed
        // TODO add your handling code here:
        pare.interrupt();
        
        try{
            Thread.sleep(50);
        }
        catch(Exception e){}
        
        dispose();
    }//GEN-LAST:event_BGoActionPerformed

    private void RuletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuletActionPerformed
       if (Rulet.getSelectedItem().equals("LloydC")){
                      
           PCombo.setEnabled(true);
           
           
           if (Rulet2.getSelectedItem().equals("LloydC") && !PCombo2.isEnabled()) PCombo2.setEnabled(true);
           
       }
       else if (Rulet.getSelectedItem().equals("Random")){
           
           prof1 = 0;
           PCombo.setSelectedItem("0");
           PCombo.setEnabled(false);
           
       }
       
       else{
           prof1 = 0;
           PCombo.setSelectedItem("0");
           PCombo.setEnabled(false);
           
           if (Rulet2.getSelectedItem().equals("LloydC")){
               if (!PCombo2.isEnabled()) PCombo2.setEnabled(true);
           }
           
       }
       
       user1 = Rulet.getSelectedItem().toString();
       
       
           
            
    }//GEN-LAST:event_RuletActionPerformed

    private void PCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCombo2ActionPerformed
        // TODO add your handling code here:
        prof2=Integer.parseInt(PCombo2.getItemAt(PCombo2.getSelectedIndex()));
       
    }//GEN-LAST:event_PCombo2ActionPerformed

    private void Rulet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rulet2ActionPerformed
       if (Rulet2.getSelectedItem().equals("LloydC")){
           
           PCombo2.setEnabled(true);
           
           if (Rulet.getSelectedItem().equals("LloydC") && !PCombo.isEnabled()) PCombo.setEnabled(true);
           
       }
       else if (Rulet2.getSelectedItem().equals("Random")){
           
           prof2 = 0;
           PCombo2.setSelectedItem("0");
           PCombo2.setEnabled(false);
       }
       
       else{
           
           if (Rulet.getSelectedItem().equals("LloydC")){
               if (!PCombo.isEnabled()) PCombo.setEnabled(true);
           }
           
           
           prof2 = 0;
           PCombo2.setSelectedItem("0");
           PCombo2.setEnabled(false);
           
       }
       
       user2 = Rulet2.getSelectedItem().toString();
       
        
        
    }//GEN-LAST:event_Rulet2ActionPerformed

    private void PComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PComboActionPerformed
        // TODO add your handling code here:
        prof1= Integer.parseInt(PCombo.getItemAt(PCombo.getSelectedIndex()));
    }//GEN-LAST:event_PComboActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGo;
    private javax.swing.JComboBox<String> PCombo;
    private javax.swing.JComboBox<String> PCombo2;
    private javax.swing.JComboBox<String> Rulet;
    private javax.swing.JComboBox<String> Rulet2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
