package Interface;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;


/**
 *
 * @author Hume
 */
public class Tauler extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Tauler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fill_15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_05 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_76 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_66 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_56 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_46 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_36 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_06 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_71 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_73 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_61 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_51 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_41 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_31 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_03 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_23 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_33 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_43 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_01 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_77 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_67 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_57 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_53 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_63 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_47 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_37 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_74 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_27 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_64 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_54 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_07 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_44 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_34 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_24 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_04 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_70 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_60 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_50 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_40 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_72 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_62 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_20 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_52 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_00 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_42 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_22 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_02 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_75 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_65 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_55 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_45 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_35 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        fill_25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Versus");

        jLayeredPane1.setBackground(new java.awt.Color(198, 255, 0));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane1MouseClicked(evt);
            }
        });

        fill_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_15.setOpaque(true);
        jLayeredPane1.add(fill_15);
        fill_15.setBounds(290, 390, 50, 50);

        fill_05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_05.setOpaque(true);
        jLayeredPane1.add(fill_05);
        fill_05.setBounds(290, 440, 50, 50);

        fill_76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_76.setOpaque(true);
        jLayeredPane1.add(fill_76);
        fill_76.setBounds(340, 90, 50, 50);

        fill_66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_66.setOpaque(true);
        jLayeredPane1.add(fill_66);
        fill_66.setBounds(340, 140, 50, 50);

        fill_56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_56.setOpaque(true);
        jLayeredPane1.add(fill_56);
        fill_56.setBounds(340, 190, 50, 50);

        fill_46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_46.setOpaque(true);
        jLayeredPane1.add(fill_46);
        fill_46.setBounds(340, 240, 50, 50);

        fill_36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_36.setOpaque(true);
        jLayeredPane1.add(fill_36);
        fill_36.setBounds(340, 290, 50, 50);

        fill_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_26.setOpaque(true);
        jLayeredPane1.add(fill_26);
        fill_26.setBounds(340, 340, 50, 50);

        fill_16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_16.setOpaque(true);
        jLayeredPane1.add(fill_16);
        fill_16.setBounds(340, 390, 50, 50);

        fill_06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_06.setOpaque(true);
        jLayeredPane1.add(fill_06);
        fill_06.setBounds(340, 440, 50, 50);

        fill_71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_71.setOpaque(true);
        jLayeredPane1.add(fill_71);
        fill_71.setBounds(90, 90, 50, 50);

        fill_73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_73.setOpaque(true);
        jLayeredPane1.add(fill_73);
        fill_73.setBounds(190, 90, 50, 50);

        fill_61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_61.setOpaque(true);
        jLayeredPane1.add(fill_61);
        fill_61.setBounds(90, 140, 50, 50);

        fill_51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_51.setOpaque(true);
        jLayeredPane1.add(fill_51);
        fill_51.setBounds(90, 190, 50, 50);

        fill_41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_41.setOpaque(true);
        jLayeredPane1.add(fill_41);
        fill_41.setBounds(90, 240, 50, 50);

        fill_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_31.setOpaque(true);
        jLayeredPane1.add(fill_31);
        fill_31.setBounds(90, 290, 50, 50);

        fill_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_21.setOpaque(true);
        jLayeredPane1.add(fill_21);
        fill_21.setBounds(90, 340, 50, 50);

        fill_03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_03.setOpaque(true);
        jLayeredPane1.add(fill_03);
        fill_03.setBounds(190, 440, 50, 50);

        fill_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_13.setOpaque(true);
        jLayeredPane1.add(fill_13);
        fill_13.setBounds(190, 390, 50, 50);

        fill_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_23.setOpaque(true);
        jLayeredPane1.add(fill_23);
        fill_23.setBounds(190, 340, 50, 50);

        fill_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_33.setOpaque(true);
        jLayeredPane1.add(fill_33);
        fill_33.setBounds(190, 290, 50, 50);

        fill_43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_43.setOpaque(true);
        jLayeredPane1.add(fill_43);
        fill_43.setBounds(190, 240, 50, 50);

        fill_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_11.setOpaque(true);
        jLayeredPane1.add(fill_11);
        fill_11.setBounds(90, 390, 50, 50);

        fill_01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_01.setOpaque(true);
        jLayeredPane1.add(fill_01);
        fill_01.setBounds(90, 440, 50, 50);

        fill_77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_77.setOpaque(true);
        jLayeredPane1.add(fill_77);
        fill_77.setBounds(390, 90, 50, 50);

        fill_67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_67.setOpaque(true);
        jLayeredPane1.add(fill_67);
        fill_67.setBounds(390, 140, 50, 50);

        fill_57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_57.setOpaque(true);
        jLayeredPane1.add(fill_57);
        fill_57.setBounds(390, 190, 50, 50);

        fill_53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_53.setOpaque(true);
        jLayeredPane1.add(fill_53);
        fill_53.setBounds(190, 190, 50, 50);

        fill_63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_63.setOpaque(true);
        jLayeredPane1.add(fill_63);
        fill_63.setBounds(190, 140, 50, 50);

        fill_47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_47.setOpaque(true);
        jLayeredPane1.add(fill_47);
        fill_47.setBounds(390, 240, 50, 50);

        fill_37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_37.setOpaque(true);
        jLayeredPane1.add(fill_37);
        fill_37.setBounds(390, 290, 50, 50);

        fill_74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_74.setOpaque(true);
        jLayeredPane1.add(fill_74);
        fill_74.setBounds(240, 90, 50, 50);

        fill_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_27.setOpaque(true);
        jLayeredPane1.add(fill_27);
        fill_27.setBounds(390, 340, 50, 50);

        fill_64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_64.setOpaque(true);
        jLayeredPane1.add(fill_64);
        fill_64.setBounds(240, 140, 50, 50);

        fill_17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_17.setOpaque(true);
        jLayeredPane1.add(fill_17);
        fill_17.setBounds(390, 390, 50, 50);

        fill_54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_54.setOpaque(true);
        jLayeredPane1.add(fill_54);
        fill_54.setBounds(240, 190, 50, 50);

        fill_07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_07.setOpaque(true);
        jLayeredPane1.add(fill_07);
        fill_07.setBounds(390, 440, 50, 50);

        fill_44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_44.setOpaque(true);
        jLayeredPane1.add(fill_44);
        fill_44.setBounds(240, 240, 50, 50);

        fill_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_34.setOpaque(true);
        jLayeredPane1.add(fill_34);
        fill_34.setBounds(240, 290, 50, 50);

        fill_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_24.setOpaque(true);
        jLayeredPane1.add(fill_24);
        fill_24.setBounds(240, 340, 50, 50);

        fill_14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_14.setOpaque(true);
        jLayeredPane1.add(fill_14);
        fill_14.setBounds(240, 390, 50, 50);

        fill_04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_04.setOpaque(true);
        jLayeredPane1.add(fill_04);
        fill_04.setBounds(240, 440, 50, 50);

        fill_70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_70.setOpaque(true);
        jLayeredPane1.add(fill_70);
        fill_70.setBounds(40, 90, 50, 50);

        fill_60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_60.setOpaque(true);
        jLayeredPane1.add(fill_60);
        fill_60.setBounds(40, 140, 50, 50);

        fill_50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_50.setOpaque(true);
        jLayeredPane1.add(fill_50);
        fill_50.setBounds(40, 190, 50, 50);

        fill_40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_40.setOpaque(true);
        jLayeredPane1.add(fill_40);
        fill_40.setBounds(40, 240, 50, 50);

        fill_30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_30.setOpaque(true);
        jLayeredPane1.add(fill_30);
        fill_30.setBounds(40, 290, 50, 50);

        fill_72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_72.setOpaque(true);
        jLayeredPane1.add(fill_72);
        fill_72.setBounds(140, 90, 50, 50);

        fill_62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_62.setOpaque(true);
        jLayeredPane1.add(fill_62);
        fill_62.setBounds(140, 140, 50, 50);

        fill_20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_20.setOpaque(true);
        jLayeredPane1.add(fill_20);
        fill_20.setBounds(40, 340, 50, 50);

        fill_10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_10.setOpaque(true);
        jLayeredPane1.add(fill_10);
        fill_10.setBounds(40, 390, 50, 50);

        fill_52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_52.setOpaque(true);
        jLayeredPane1.add(fill_52);
        fill_52.setBounds(140, 190, 50, 50);

        fill_00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_00.setOpaque(true);
        jLayeredPane1.add(fill_00);
        fill_00.setBounds(40, 440, 50, 50);

        fill_42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_42.setOpaque(true);
        jLayeredPane1.add(fill_42);
        fill_42.setBounds(140, 240, 50, 50);

        fill_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_32.setOpaque(true);
        jLayeredPane1.add(fill_32);
        fill_32.setBounds(140, 290, 50, 50);

        fill_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_22.setOpaque(true);
        jLayeredPane1.add(fill_22);
        fill_22.setBounds(140, 340, 50, 50);

        fill_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_12.setOpaque(true);
        jLayeredPane1.add(fill_12);
        fill_12.setBounds(140, 390, 50, 50);

        fill_02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_02.setOpaque(true);
        jLayeredPane1.add(fill_02);
        fill_02.setBounds(140, 440, 50, 50);

        fill_75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_75.setOpaque(true);
        jLayeredPane1.add(fill_75);
        fill_75.setBounds(290, 90, 50, 50);

        fill_65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_65.setOpaque(true);
        jLayeredPane1.add(fill_65);
        fill_65.setBounds(290, 140, 50, 50);

        fill_55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_55.setOpaque(true);
        jLayeredPane1.add(fill_55);
        fill_55.setBounds(290, 190, 50, 50);

        fill_45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_45.setOpaque(true);
        jLayeredPane1.add(fill_45);
        fill_45.setBounds(290, 240, 50, 50);

        fill_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_35.setOpaque(true);
        jLayeredPane1.add(fill_35);
        fill_35.setBounds(290, 290, 50, 50);

        fill_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fill_25.setOpaque(true);
        jLayeredPane1.add(fill_25);
        fill_25.setBounds(290, 340, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int c1, c2;
    private static int[][] tauler = { {0, 0, 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0, 0}};
    static double Ymax;
    static double  Xmax;
    static int  Step;
    static boolean Torn;
    
    private static int whichx(int col){
        return (Step*col+70);
    }
    
    private static int whichy(int fil){
        return (446-fil*50);
    }

    private void jLayeredPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane1MouseClicked
        // TODO add your handling code here:

        int X = evt.getX();
        int Y = evt.getY();
        Dimension mides = jLayeredPane1.getSize();
        Ymax = mides.getHeight();
        Xmax = mides.getWidth();
        Step = (int) Xmax/8;
        int col = (int) X/Step;
        jTextField1.setText(String.valueOf(col));

        if (!Torn){
            col =(int) (8*Math.random());
        }       
        int j=0;
        boolean trobat=false;
        while (j<8 && !trobat){
            if (tauler[col][j]!=0){ 
                    j++;
            }
            else{
                trobat=true;
            }
        }
        if (trobat){
        if (Torn) {
            tauler[col][j]=1;
            Torn = !(Torn);
        }
        else {
            tauler[col][j]=-1;
            Torn = !(Torn);
        }
        }
        repaint();
    }//GEN-LAST:event_jLayeredPane1MouseClicked

    
    private static  void movimentrandom(){
        int j=0;
        boolean trobat=false;
        int col =(int) (8*Math.random());
        while (j<8 && !trobat){
            if (tauler[col][j]!=0){ 
                    j++;
            }
            else{
                trobat=true;
            }
        }
        if (trobat){
        if (Torn) {
            tauler[col][j]=1;
            Torn = !(Torn);
        }
        else {
            tauler[col][j]=-1;
            Torn = !(Torn);
        }
        }
      //  repaint();
    }
    
    @Override
    public void paint(Graphics g)
    {
     super.paint(g);
     for (int i=0; i<8; i++){
        for (int j=0; j<8; j++){
            if (tauler[i][j]==1) { 
                g.setColor(Color.BLACK);
                g.drawOval(whichx(i),whichy(j),40,40);
                g.fillOval(whichx(i),whichy(j),40,40);
            }
            else if (tauler[i][j]==-1) { 
                g.setColor(Color.YELLOW);
                g.drawOval(whichx(i),whichy(j),40,40);
                g.fillOval(whichx(i),whichy(j),40,40);
            }
        }
     }
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fill_00;
    private javax.swing.Box.Filler fill_01;
    private javax.swing.Box.Filler fill_02;
    private javax.swing.Box.Filler fill_03;
    private javax.swing.Box.Filler fill_04;
    private javax.swing.Box.Filler fill_05;
    private javax.swing.Box.Filler fill_06;
    private javax.swing.Box.Filler fill_07;
    private javax.swing.Box.Filler fill_10;
    private javax.swing.Box.Filler fill_11;
    private javax.swing.Box.Filler fill_12;
    private javax.swing.Box.Filler fill_13;
    private javax.swing.Box.Filler fill_14;
    private javax.swing.Box.Filler fill_15;
    private javax.swing.Box.Filler fill_16;
    private javax.swing.Box.Filler fill_17;
    private javax.swing.Box.Filler fill_20;
    private javax.swing.Box.Filler fill_21;
    private javax.swing.Box.Filler fill_22;
    private javax.swing.Box.Filler fill_23;
    private javax.swing.Box.Filler fill_24;
    private javax.swing.Box.Filler fill_25;
    private javax.swing.Box.Filler fill_26;
    private javax.swing.Box.Filler fill_27;
    private javax.swing.Box.Filler fill_30;
    private javax.swing.Box.Filler fill_31;
    private javax.swing.Box.Filler fill_32;
    private javax.swing.Box.Filler fill_33;
    private javax.swing.Box.Filler fill_34;
    private javax.swing.Box.Filler fill_35;
    private javax.swing.Box.Filler fill_36;
    private javax.swing.Box.Filler fill_37;
    private javax.swing.Box.Filler fill_40;
    private javax.swing.Box.Filler fill_41;
    private javax.swing.Box.Filler fill_42;
    private javax.swing.Box.Filler fill_43;
    private javax.swing.Box.Filler fill_44;
    private javax.swing.Box.Filler fill_45;
    private javax.swing.Box.Filler fill_46;
    private javax.swing.Box.Filler fill_47;
    private javax.swing.Box.Filler fill_50;
    private javax.swing.Box.Filler fill_51;
    private javax.swing.Box.Filler fill_52;
    private javax.swing.Box.Filler fill_53;
    private javax.swing.Box.Filler fill_54;
    private javax.swing.Box.Filler fill_55;
    private javax.swing.Box.Filler fill_56;
    private javax.swing.Box.Filler fill_57;
    private javax.swing.Box.Filler fill_60;
    private javax.swing.Box.Filler fill_61;
    private javax.swing.Box.Filler fill_62;
    private javax.swing.Box.Filler fill_63;
    private javax.swing.Box.Filler fill_64;
    private javax.swing.Box.Filler fill_65;
    private javax.swing.Box.Filler fill_66;
    private javax.swing.Box.Filler fill_67;
    private javax.swing.Box.Filler fill_70;
    private javax.swing.Box.Filler fill_71;
    private javax.swing.Box.Filler fill_72;
    private javax.swing.Box.Filler fill_73;
    private javax.swing.Box.Filler fill_74;
    private javax.swing.Box.Filler fill_75;
    private javax.swing.Box.Filler fill_76;
    private javax.swing.Box.Filler fill_77;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
